name: Test - E2E - EnvTest with Cluster # e2e tests running against a k8s cluster

on:
  pull_request:
    branches:
    - main
    types:
    - opened
    - reopened
    - synchronize
    - closed

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  minikube-default:
    name: Run e2e tests against Minikube
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flux CLI # used in the make command
        uses: fluxcd/flux2/action@main

      - name: Run e2e tests against current cluster
        run: |
          make test-e2e-with-cluster-local

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3

  minikube-tainted:
    name: Run e2e tests against Minikube (TAINTED)
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Run e2e tests against current tainted cluster
        run: |
          make test-e2e-with-tainted-cluster-local

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
