name: Test - Lint Helm Chart and Go Test

on:
  pull_request:
    branches:
    - main

jobs:
  lint-helm-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Helm Chart
        run: |
          make helm-lint
